SELECT OUTS.ANIMAL_ID, OUTS.NAME -- OUTS의 ANIMAL_ID, NAME 조회
    FROM ANIMAL_OUTS AS OUTS
        LEFT OUTER JOIN ANIMAL_INS AS INS
        ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
        WHERE INS.ANIMAL_ID IS NULL; -- INS.ANIMAL_ID가 NULL인 경우 제외