-- 전체 동물 중 입양된 동물은 OUTS에만 기록돼 있음. 
SELECT INS.NAME, INS.DATETIME
    FROM ANIMAL_INS AS INS
        LEFT OUTER JOIN ANIMAL_OUTS AS OUTS
        ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
        WHERE OUTS.ANIMAL_ID IS NULL
        ORDER BY INS.DATETIME
        LIMIT 3; -- 3마리 제한. LIMIT 0, 3와 LIMIT 3 OFFSET 0와 동일