SELECT OUTS.ANIMAL_ID, OUTS.NAME -- ID, 이름 조회
    FROM ANIMAL_OUTS AS OUTS 
        INNER JOIN ANIMAL_INS AS INS -- 둘다 있는 경우만 조회하므로 INNER JOIN
        ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
        ORDER BY (OUTS.DATETIME - INS.DATETIME) DESC -- 내림차순으로 
        LIMIT 2; -- 2개만