-- ORDER BY : 조건에 따라 정렬
SELECT CITY, LENGTH(CITY)  FROM STATION
    ORDER BY LENGTH(CITY), CITY
    LIMIT 1;
  
SELECT CITY, LENGTH(CITY)  FROM STATION
    ORDER BY LENGTH(CITY) DESC, CITY DESC
    LIMIT 1;